import type { SelectOption } from "@/components/SelectOptionsModal";

// Common breeds in France; any other breed can still be typed in the field.
const BREEDS: readonly string[] = [
  "Akhal-Téké",
  "Andalou",
  "Anglo-arabe",
  "Appaloosa",
  "Arabe",
  "Ardennais",
  "Auxois",
  "Barbe",
  "Boulonnais",
  "Breton",
  "Camargue",
  "Cheval de selle irlandais",
  "Cob normand",
  "Comtois",
  "Connemara",
  "Fjord",
  "Franches-Montagnes",
  "Frison",
  "Hackney",
  "Haflinger",
  "Hanovrien",
  "Henson",
  "Holsteiner",
  "Islandais",
  "KWPN",
  "Lipizzan",
  "Lusitanien",
  "Mustang",
  "Mérens",
  "New Forest",
  "Oldenbourg",
  "Paint Horse",
  "Percheron",
  "Poney français de selle",
  "Pottok",
  "Pur-sang anglais",
  "Quarter Horse",
  "Selle français",
  "Shetland",
  "Shire",
  "Trakehner",
  "Trotteur français",
  "Welsh",
];

export const BREED_OPTIONS: readonly SelectOption[] = BREEDS.map((breed) => ({
  label: breed,
  value: breed,
}));
